### ISSUE TITLE
Error when going to /hooks

### ISSUE THREAD

**Issue by fagnercarvalho** [ValeraT1982/react-data-load#1]
I'm getting an error when going to /hooks. The route loads the data correctly but when I try to go to another route I get a blank page.

Here is the error I get in /hooks:

```
index.js:1446 Warning: An effect function must not return anything besides a function, which is used for clean-up.

It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:

useEffect(() => {
  async function fetchData() {
    // You can await here
    const response = await MyAPI.getData(someId);
    // ...
  }
  fetchData();
}, [someId]); // Or [] if effect doesn't need props or state
```

I was able to fix this error if I follow the suggestion described above. I just need to replace the following code in UsersWithHooks.js from:

```
useEffect(async () => {
	try {
		const response = await Api.getUsers();
		const json = await response.json();

		setData(json);
	} catch (e) {
		setError(e.message || 'Unexpected error');
	}

	setLoading(false);
}, []);
```

To:

```
useEffect(() => {
	async function fetchData() {
		try {
			const response = await Api.getUsers();
			const json = await response.json();

			setData(json);
		} catch (e) {
			setError(e.message || 'Unexpected error');
		}

		setLoading(false);
	}
	fetchData();
}, []);
```

My questions are:
- I'm learning React right now and this was the better example about data fetching I found. Simple and straightforward. However since your article related to this example was made one year ago I wonder if this needs an update. Is this the most up to date way to fetch data in React?
- Can you update this example with my fix to the issue? I can also make a PR if you want.

**Comment by ValeraT1982** [comment]
@fagnercarvalho, to be honest I didn't follow react news very close during the last half a year, but I think that examples from the article are mostly up to date and accurate. Example with hooks used to work, maybe it doesn't work with the latest version of the react.

I'd appreciate if you make a PR to fix it. I'm going to have a closer look this week.

**Comment by ValeraT1982** [comment]
@fagnercarvalho, it's warning, not an error. Everything works. I changed the code according your suggestion to get rid of warning.

Thanks a lot!
